# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/lunaa/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),lunaa)

$(call add-radio-file-sha1-checked,radio/abl.img,1f957a7dab64658e95c78539a7838f77e1721701)
$(call add-radio-file-sha1-checked,radio/aop.img,c766c53437c8fc507edcfdbee89a0ee484658a98)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,9d6c19963b0180947c716ce1e58b4f719b268dd1)
$(call add-radio-file-sha1-checked,radio/cpucp.img,47ab1fafc795d0a66d4e7958fd0c738c7d57baf1)
$(call add-radio-file-sha1-checked,radio/devcfg.img,a186ba3cfb0da7b8a8889273518630be6228ae53)
$(call add-radio-file-sha1-checked,radio/dsp.img,a76815c20c47a0931609dc3c5bab3a7d8c492da0)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,54f65de7d7f7335b14440f690630e32de1b37824)
$(call add-radio-file-sha1-checked,radio/hyp.img,163d85a03802ec8098d39f2fb495c1acfab4d437)
$(call add-radio-file-sha1-checked,radio/imagefv.img,c56f0cbade3cc75d4ffd7716ae66bfcb9bf64b3c)
$(call add-radio-file-sha1-checked,radio/keymaster.img,f7949cb6927ed7d5c88b9cb9be19c98333e9dfd3)
$(call add-radio-file-sha1-checked,radio/modem.img,57eee588154d539106d97e7bf528202eed23a463)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,04a8f1f8b9e53711636d71759b729dfbf4477388)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,42a2126a04a8e2372342b01f070b24acbf295c94)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,878bb18b0014a9d2eb3a84de54f5c97c096c4fbc)
$(call add-radio-file-sha1-checked,radio/qupfw.img,8e806f9c0cbcb85d59f8e2c047bbbe83ee690850)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,53d5852dee35d60e79020be673116319dee92b97)
$(call add-radio-file-sha1-checked,radio/splash.img,d316941bfde9cc9180158fdafab46dd04310e81d)
$(call add-radio-file-sha1-checked,radio/tz.img,3c9d3896a575ee608c161777de0fa4cc2e92c9b1)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,9b5a959b5a7d504b5b44d79234cee9d8f8589742)
$(call add-radio-file-sha1-checked,radio/xbl.img,7f2e954644ffe70eafe86fd0449e78bf7a4d2109)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,a0de60082f07bc3e66adc679a840404b00b57576)

endif
