# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/lunaa/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),lunaa)

$(call add-radio-file-sha1-checked,radio/abl.img,7ad60275d2a411e2fbc50b8f4728aad6ee1f6396)
$(call add-radio-file-sha1-checked,radio/aop.img,51fd417681d8fdc9272f509e56348f2cb808d297)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,7547de7315204ad26e96c92571898c2ffd02c04d)
$(call add-radio-file-sha1-checked,radio/cpucp.img,7bdf8790a6b676940735a638e5ec083fd9eb6367)
$(call add-radio-file-sha1-checked,radio/devcfg.img,8f189d8c499626c051d07c3d9393546dde76efc1)
$(call add-radio-file-sha1-checked,radio/dsp.img,a76815c20c47a0931609dc3c5bab3a7d8c492da0)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,1787dd071efbe7ec4b470bef7aee13e06a31f132)
$(call add-radio-file-sha1-checked,radio/hyp.img,bc47af7e7767bb3cb09fa41ed65ec65a43207e61)
$(call add-radio-file-sha1-checked,radio/imagefv.img,34fbe5607c68e110260e4aee1e797c9ce410422a)
$(call add-radio-file-sha1-checked,radio/keymaster.img,52db89db26303d78cbbba863db018deb4032af12)
$(call add-radio-file-sha1-checked,radio/modem.img,152260b16a31549a2639afed380a595c6e780498)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,5bd1eb30ae21f5b9192c9b87c8c8d08d3e6681cd)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,42a2126a04a8e2372342b01f070b24acbf295c94)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,672d53e1184d96dc271ee34c01f28219defd9068)
$(call add-radio-file-sha1-checked,radio/qupfw.img,31effa0977c303ac5f86d13eeb85f60948433835)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,8ab832ca621113fc3ded7940d24fb26059a0be26)
$(call add-radio-file-sha1-checked,radio/splash.img,d316941bfde9cc9180158fdafab46dd04310e81d)
$(call add-radio-file-sha1-checked,radio/tz.img,e0d7c4f2416bab2ab50f211211ab8a7336c7a967)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,65517b7264536d2b909f22a71eb5b3cb33393248)
$(call add-radio-file-sha1-checked,radio/xbl.img,718553f7ba42c82e83f3b8d4756d7cbff7305fcb)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,bf2c9a0717a5a43b93438129dc4c6d76e646d0d8)

endif
