# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/lunaa/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),lunaa)

$(call add-radio-file-sha1-checked,radio/abl.img,630ae121e0853ede7a130f007fb9471e90c5cd1e)
$(call add-radio-file-sha1-checked,radio/aop.img,54efc145156e7ae6e94dc9a40b7758a98ee243d9)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,46a45e9d2291bcc16c03deb8ebf80ffa5e11eb2f)
$(call add-radio-file-sha1-checked,radio/cpucp.img,b0975980e3b384756817edefd9b88ec3251c40ab)
$(call add-radio-file-sha1-checked,radio/devcfg.img,e7275dce32a24076067da317bdf611ce75683b75)
$(call add-radio-file-sha1-checked,radio/dsp.img,a76815c20c47a0931609dc3c5bab3a7d8c492da0)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,2ca351099c475864a03f9417c337e52b07a6282a)
$(call add-radio-file-sha1-checked,radio/hyp.img,c3fa97abd618a45f546e7a74443788100b700469)
$(call add-radio-file-sha1-checked,radio/imagefv.img,f7604c6abb6e0b22fb5ab3178b8bfeb5f7235399)
$(call add-radio-file-sha1-checked,radio/keymaster.img,876aa13c1086ea2f0221713a9f27262bca638610)
$(call add-radio-file-sha1-checked,radio/modem.img,93fcf08f85882cc6378304f4afcfa6967ab3030c)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,06f7ba74209a86b66f728bfd91266404d1d51ec4)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,42a2126a04a8e2372342b01f070b24acbf295c94)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,d3dfaf0bdc7957e3a6a6a5c741c872f4348e945a)
$(call add-radio-file-sha1-checked,radio/qupfw.img,ad4c37a91d17393278ab4deb7abf7bd2e976ff72)
$(call add-radio-file-sha1-checked,radio/qweslicstore.img,180cf2903b9872499d05eeef08c472575fa3225e)
$(call add-radio-file-sha1-checked,radio/shrm.img,45d784ca28ac068c1a3414295b2141203551b284)
$(call add-radio-file-sha1-checked,radio/splash.img,d316941bfde9cc9180158fdafab46dd04310e81d)
$(call add-radio-file-sha1-checked,radio/tz.img,ed76ff865172ebf1300c03e2d6c814b527a3197e)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,5e8a798b13d25e951182105816db85b4f0953639)
$(call add-radio-file-sha1-checked,radio/xbl.img,ae82bdffa43742a768cfbaa64f2001d985cf6317)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,7a6de667d02f7fcd5710ad71e9b2e560e2bd784d)

endif
